directories:
  output: dist-electron
  buildResources: build
appId: com.hamradiologger.app
productName: Ham Radio Logger
win:
  target:
    - nsis
  icon: public/icon.ico
mac:
  target:
    - dmg
  icon: public/icon.icns
linux:
  target:
    - AppImage
  icon: public/icon.png
files: []
electronVersion: 29.4.6
